language: rust

rust:
  - 1.17.0
  - stable
  - beta

cache: cargo

script:
  - cargo build --verbose --all --features "${FEATURES}"
  - cargo test --verbose --all --features "${FEATURES}"

env:
  - FEATURES=""
  - FEATURES="extprim"

matrix:
  allow_failures:
    - rust: nightly
