language: rust

rust:
  - 1.17.0
  - stable
  - beta
  - nightly

cache: cargo

script:
  - cargo build --verbose --all --features "${FEATURES}"
  - cargo test --verbose --all --features "${FEATURES}"
  - [ "${TRAVIS_RUST_VERSION}" = nightly ] && cargo bench --no-run --all --features "${FEATURES}"

env:
  - FEATURES=""
  - FEATURES="extprim"

matrix:
  allow_failures:
    - rust: nightly
