[package]
name = "serde_mtproto"
version = "0.1.0"
description = "MTProto [de]serialization for Rust"
authors = ["Nguyen Duc My <hcpl.prog@gmail.com>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/hcpl/serde_mtproto"
documentation = "https://docs.rs/serde_mtproto"
repository = "https://github.com/hcpl/serde_mtproto"

[dependencies]
byteorder = "1.1.0"
error-chain = "0.10.0"
serde = "1.0.11"
serde_derive = "1.0.11"
