[package]
name = "serde_mtproto"
version = "0.2.0"
description = "MTProto [de]serialization for Rust"
authors = ["Nguyen Duc My <hcpl.prog@gmail.com>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/hcpl/serde_mtproto"
documentation = "https://docs.rs/serde_mtproto"
repository = "https://github.com/hcpl/serde_mtproto"
keywords = ["serde", "serialization", "telegram"]

[dependencies]
byteorder = "1.1.0"
error-chain = "0.10.0"
num-traits = "0.1.40"
serde = "1.0.11"
serde_derive = "1.0.11"

[dev-dependencies]
lazy_static = "0.2.8"
maplit = "0.1.4"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_mtproto_derive = { path = "serde_mtproto_derive", version = "0.2.0" }
