[package]
name = "serde_mtproto"
version = "0.3.1"
description = "MTProto [de]serialization for Rust"
authors = ["Nguyen Duc My <hcpl.prog@gmail.com>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/hcpl/serde_mtproto"
documentation = "https://docs.rs/serde_mtproto"
repository = "https://github.com/hcpl/serde_mtproto"
keywords = ["serde", "serialization", "telegram"]

[badges]
travis-ci = { repository = "hcpl/serde_mtproto" }

[workspace]
members = ["serde_mtproto_derive"]

[dependencies]
byteorder = "1.1.0"
error-chain = "0.11.0"
extprim = { version = "1.4.0", optional = true }
log = "0.3.8"
num-traits = "0.1.40"
serde = "1.0.12"
serde_bytes = "0.10.2"
serde_derive = "1.0.12"

[dev-dependencies]
lazy_static = "0.2.8"
lipsum = "0.3.0"
maplit = "0.1.4"
pretty_assertions = "0.3.4"
rand = "0.3.16"
rand_derive = "0.3.1"
serde_json = "1.0.3"
serde_mtproto_derive = { path = "serde_mtproto_derive", version = "0.3.1" }
